2020年 05月 09日 星期六 18:33:32 CST

diff --git a/bin/sync_upstream b/bin/sync_upstream
--- a/bin/sync_upstream
+++ b/bin/sync_upstream
@@ -1,30 +1,38 @@
 #!/bin/bash
 # https://gist.github.com/Juraci/d1414f7c780e2dbe8204
+# modified by klkyy2020(klkyy2020 at 163 dot com)
 
 red=$(tput setaf 1)
 green=$(tput setaf 2)
 yellow=$(tput setaf 3)
-upstream=$1
+
+myexit() {
+  reason=$1
+  printf "${red}Failed: ${reason}!!!\n"
+  exit 1
+}
+
+
+# default "`pwd`"
+repo_path=$1
+[ -z ${repo_path} ] && repo_path=`pwd`
+[ -d $repo_path ] || myexit "First parameter is not directory"
+# default "master"
 branch=$2
+
+# checks if it's a git repo
+check_repo() {
+  if [ ! -d `pwd`/.git ]; then
+    myexit "`pwd` is not a git repo"
+  fi 
+}
 
 # checks if there is a remote repo called upstream
 check_upstream() {
-  git remote -v | grep upstream
+  git remote -v | grep -w upstream > /dev/null
   # if there are no remote repository called upstream
   if [ $? -ne 0 ]; then
-    printf "${red}Upstream not configured\n"
-    # if the url was passed as an parameter, adds a remote repo called upstream pointing to that url
-    if [[ $upstream ]]; then
-      printf "${yellow}Upstream URL will be set to ${upstream}\n"
-      git remote add upstream $upstream
-    else
-      # if there is no remote called upstream and no url was passed aborts the whole thing
-      printf "${red}Upstream parameter not informed, please inform it like this:\n\n${yellow}--> bash sync-upstream <upstream-url> <branch-to-sync-from>\n\n"
-      printf "${yellow}This is an one time configuration (for each forked repository)\n\n"
-      exit 1
-    fi
-  else
-    printf "${green}Upstream seems to be configured\n"
+    myexit "Upstream not configured in this repo(`pwd`)"
   fi
 }
 
@@ -49,10 +57,14 @@ sync() {
     git merge upstream/$branch
     git push
   else
-    printf "${red}"
+    myexit "Failed fetch upstream"
   fi
 }
 
+cur_path=`pwd`
+cd $repo_path
+check_repo
 check_upstream
 check_branch
 sync
+printf "${green}Succ!!!\n"
